services:
  - type: worker
    name: telegram-drive-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
